[package]
name = "iced-myterm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alacritty_terminal = "0.20.0"
iced = { version = "0.10.0", features = ["smol", "tokio", "canvas", "wgpu", "lazy"] }
tokio = { version = "1.23.0", features = ["full"]}
ab_glyph = { default-features = false, features = ["libm"] }
