[package]
name = "iced-myterm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alacritty_terminal = "0.20.0"
iced = { version = "0.10.0", features = ["smol", "tokio", "canvas", "wgpu", "advanced"] }

#iced_native = "0.10.3"
#iced_wgpu = "0.11.1"
#iced_graphics = "0.9.0"
tokio = { version = "1.23.0", features = ["fs", "process", "io-util"]}
